### ISSUE TITLE
Rustの実装について。tokio::sync::RwLockを試してみてください

### ISSUE THREAD

**Issue by tatsuya6502** [ynaka81/in_memory_db_comparison#1]
こんにちは。こちらの記事を興味深く拝見しました。
- [Go vs Rust : 特徴量DBに適するのはどっち！？](https://tech-blog.abeja.asia/entry/2020/04/09/115152)

私はRustのことしかわからないので、Rustの実装で気になった点をお伝えしますね。

いまの実装ではDBのロックに`std::sync::RwLock`を使われていますが、今回のユースケースでは別の`RwLock`実装の一つである`tokio::sync::RwLock`を使った方がいいと思います。`std::sync::RwLock`には以下のような特性があり、それらが性能劣化を招いているのかなと考えました。

1. ロックポリシーがOS依存。Linuxだとwriter starvationといって、readロックが優先されて、writeロックがなかなか取れないという現象が起こりやすい。
2. 非同期API（`async/.await`）に非対応。ロック待ちになるとスレッドをブロックしてしまい、他の非同期タスクに切り替わらない。非同期に対応している`RwLock`なら、ロック待ちになると他の非同期タスクに切り替えてくれるのでCPUコアを効率よく使える。

おそらく、これらの特性により、以下のような性能特性が現れているのだと思います。

> 分布の外形はおおよそ同じで Go の方がやや Update が速く，Rust の方はやや Search が速いということが見て取れます．しかし，Go と Rust の言語選択に影響を与えるほど大きな違いには見えませんでした．

> 両者とも当然ですが時間経過に対して処理時間が変わることはありませんでした．長期運転をすると GC を前提とした Go の方が処理時間が跳ねてしまうことが多いのかと思いましたが，Rust の方が処理時間が跳ねることが多かったのはちょっと意外でした．とはいえ，75%タイルで見た性能はほぼ変わらないので気にするほどではなさそうです．

writer starvationによってUpdate時にロック待ちとなる時間が長くなり、全体的なUpdateの遅さや、レイテンシーのスパイクにつながっている可能性があります。また、ロック待ちの間は、その非同期タスクを実行しているスレッドがブロックされてしまうので、その間は該当するCPUコアが何もせずに休んでいる状態となり、全体的な（UpdateとSearch両方の）処理能力の低下を招いているかもしれません。

できればRwLockを`tokio::sync::RwLock`に置き換えて、再度、測定してもらえるとありがたいです。

`tokio::sync::RwLock`は非同期APIに対応していますのでスレッドをブロックしません。また、ロックポリシーとしてfairポリシーを採用していますので、writer starvationは起こりにくくなります。

https://docs.rs/tokio/0.2.16/tokio/sync/struct.RwLock.html
> The priority policy of Tokio's read-write lock is *fair* (or *write-preferring*), in order to ensure that readers cannot starve writers. Fairness is ensured using a first-in, first-out queue for the tasks awaiting the lock; if a task that wishes to acquire the write lock is at the head of the queue, read locks will not be given out until the write lock has been released. This is in contrast to the Rust standard library's `std::sync::RwLock`, where the priority policy is dependent on the operating system's implementation.

性能がどの程度改善されるか（あるいは改善されないか）は、実際に測定してみないとわかりませんが、試してみる価値はありそうです。

**Comment by tatsuya6502** [comment]
> できればRwLockを`tokio::sync::RwLock`に置き換えて、再度、測定してもらえるとありがたいです。

少し試したところ、`tokio::sync::RwLock`に置き換えたことで、かえって遅くなってしまったように見えます。もうすこし詳しく調べて、またご報告します。

**Comment by ynaka81** [comment]
@tatsuya6502 ブログを読んでいただきありがとうございます！また，ご指摘 & 検証ありがとうございます．
ぼくも軽く試してみたのですが，かえって遅くなってしまった現象が確認できたので改めて時間が取れるタイミングで調査しようと考えていました．一応，結果のグラフを貼っておきますね．

#### search
![Screenshot_2020-04-10 Performance Comparison for Async Implementation of Update](https://user-images.githubusercontent.com/13902735/79033008-b7d2e380-7be5-11ea-98f3-a59505f8a4e1.png)

#### update
![Screenshot_2020-04-10 Performance Comparison for Async Implementation of Update(1)](https://user-images.githubusercontent.com/13902735/79033014-be615b00-7be5-11ea-9c79-2f614073217d.png)

**Comment by tatsuya6502** [comment]
再測定およびグラフの作成、ありがとうございました。やはりtokioですと遅くなってますか。グラフにするとよく分かりますね。

その後、非同期APIに対応した別のRwLock実装である`async_std::sync::RwLock`も試してみました。こちらは少し高速化するようです。

現状、私の方ではログデータの集計はしていなくて、Pythonクライアントの実行にかかる時間を比べているだけですが、オリジナルの`std::sync::RwLock`による実装に比べて、以下のような結果になりました。

| RwLock | 10並列 | 20並列 |
|:---|:---|:---|
| `tokio::sync::RwLock` | 約15%低速 | 約25%低速 |
| `async_std::sync::RwLock` | 約5%高速 | 約5%高速 |

リクエスト数は1000で、Pythonクライアント、Rustサーバー共に1台のPC上で実行しています。クライアントはターミナル上にログを出すと遅くなるようなので、`StreadmHander`のところはコメントアウトしてます。

[`async_std::sync::RwLock`のドキュメント](https://docs.rs/async-std/1.5.0/async_std/sync/struct.RwLock.html)にはロックポリシーについては書かれていませんが、コードを見たところreader優先のようです。もしかすると今回のワークロードではtokioのRwLockのようなfairポリシー（writer優先）よりも、他のRwLockのようなreader優先のポリシーの方が合っているのかもしれません。

Rustサーバーは条件を変えながらテストできるように、どのRwLock実装を使うかコマンドライン引数で選べるようにしています。コードを整理してからpull requestを提出しようと思います。（これから用事があって、提出は日本時間の今夜あたりになりそうです）

**Comment by ynaka81** [comment]
ありがとうございます！やはりそういうものなのですね．PRお待ちしております．
PRを取り込んだら，RwLock 実装を変えつつブログに載せたのと同じ設定で性能をまとめて，この内容をブログに追記させていただいても良いでしょうか？

**Comment by tatsuya6502** [comment]
@ynaka81 PR #2 を提出しましたので、ご確認をお願いします。

> PRを取り込んだら，RwLock 実装を変えつつブログに載せたのと同じ設定で性能をまとめて，この内容をブログに追記させていただいても良いでしょうか？

はい。もちろんOKです。ぜひお願いします。

繰り返しになりますが、ポイントになりそうなのは以下のようなところでしょうか。

- `std::sync::RwLock`など従来のロックは非同期のしくみ（futures）に対応していないため、`async fn`や`async { }`内で使わない方がいい。
   - ロック待ちのときにTokioなどの非同期ランタイムのexecutorスレッド（Tokioではreactorと呼ばれている）をブロックしてしまうので、非同期タスクの実行の効率が低下してしまう。
   - 従来のロックを複数の `.await` にまたがって使用すると、executorスレッドがデッドロックする危険がある。（Rust公式のAsynchronous Bookでの[説明](https://rust-lang.github.io/async-book/03_async_await/01_chapter.html?highlight=lock#awaiting-on-a-multithreaded-executor)）
   - futuresに対応したロックには`async_std::lock::RwLock`や`tokio::lock::RwLock`などがある。
- 一般的にRwLockにはロックポリシーとしてreader優先とwriter優先がある。
   - 今回のワークロードではreader優先の方が向いているのかもしれない。

RustはGoのgoroutineと違い非同期タスクをライブラリで実現しているので、このロックなどがfuturesに対応しているかどうか気にしなければいけないところが面倒ですね。一度、分かってしまえば難しいことはないと思うのですが、学ばなければならないことは多いです。

あとはライブラリ自体の成熟度の問題もありますね。Rustでは頑張って書けばCやC++と同等の性能が出るプログラムが作れるのですが、C/C++の既存の成熟したライブラリと同レベルのものを作るには、知識と経験だけでなく、時間も必要になります。

Tonicもいまはpure Rustで安定して動くことを目標にしているそうで、性能面をブラッシュアップするのはまだ先のようです。

https://github.com/hyperium/tonic/issues/211

> Pretty much tonic wise there is a decent amount of work left to optimize things and the same goes for h2. Mostly, this is just the first attempt at a pure rust http/2 gRPC implementation. So I hope that once the stack starts to stabilize a bit we can put some good work into optimizing things.

このissueをオープンした人によると、grpc-rc（grpcio）クレートの性能の方がtonicよりもかなり良く、またより多くのクライアントからの接続をこなせるようです。

> The benchmark does show grpc-rs performing quite a bit better, as well as supporting a larger number of client connections. 

[grpcio](https://crates.io/crates/grpcio)クレートは公式のgRPC実装（C言語版）のRustバイディングです。

別の見方をすると、このようにCの既存ライブラリを比較的簡単に使えるのはRustの強みではあります。

**Comment by ynaka81** [comment]
PR マージしました．ありがとうございます．
また，いろいろと教えていただきありがとうございます．Rust は学ぶことが多い分，勉強するのは楽しいですね！

複数 RwLock 実装での性能差を検証したら，この issue で報告の上，ブログに追記させていただきます．

**Comment by ynaka81** [comment]
ブログと同一の環境で性能を計測し直しました．
まずは並列数に対する性能グラフですが

#### search
![Screenshot_2020-04-12 Performance Comparison for Multiple RwLock Implementation in Rust](https://user-images.githubusercontent.com/13902735/79058721-60e41180-7cac-11ea-8752-3bb61ba54992.png)

#### update
![Screenshot_2020-04-12 Performance Comparison for Multiple RwLock Implementation in Rust(1)](https://user-images.githubusercontent.com/13902735/79058722-693c4c80-7cac-11ea-9d73-73ab47540a57.png)

やはり想定通りで，`std::sync::RwLock` と `async_std::sync::RwLock` は同じような特定を示しつつ，やや後者の方が速い感じでした．

また，並列数が20の時の速度分布は

#### search
![Screenshot_2020-04-12 Performance Comparison for Multiple RwLock Implementation in Rust(2)](https://user-images.githubusercontent.com/13902735/79058739-a30d5300-7cac-11ea-843d-48c1f000d74d.png)

#### update
![Screenshot_2020-04-12 Performance Comparison for Multiple RwLock Implementation in Rust(3)](https://user-images.githubusercontent.com/13902735/79058744-aef91500-7cac-11ea-9ef1-ed6067605058.png)

こちらも`std::sync::RwLock` と `async_std::sync::RwLock` では同じ傾向を示しつつ，`tokio::sync::RwLock` だけ明らかに異なる速度分布でした．reader 優先なのか，writer 優先なのかが顕著に現れた結果が面白いですね．

この issue は close して，他の方にご指摘いただいている点も追実験した上でブログを更新させていただきます．いろいろと教えていただきありがとうございました！
