### ISSUE TITLE
gRPC に加えて REST でも行って頂くことは可能でしょうか？

### ISSUE THREAD

**Issue by ken0x0a** [ynaka81/in_memory_db_comparison#3]
最近 Actix jsonrpc と tonic grpc で性能比較したら 

Actix jsonrpc 約 140,000 req / sec (by Apache bench)
tonic grpc 約 12,000 req / sec (by ghz)

比較に使ったツールが違うのでなんとも言えないと思うのですが、
処理している内容が単純な内容に感じたため、HTTP request 周りの処理速度が結果に影響を与えているのではないかと思ったのですが、
いかがでしょうか？

**Comment by ynaka81** [comment]
なるほど，確かに実装している時も gRPC の方が本当に HTTP REST よりも速いのかは気になっていたので調査してみます．結果が出たら issue に追記しますね．

**Comment by ynaka81** [comment]
単純化のために "hello world" を返すサーバを HTTP Rest と gRPC で実装し性能を比較しました．
利用したサーバは[ブログ](https://tech-blog.abeja.asia/entry/2020/04/09/115152)と同じにして，10並列で100回繰り返して計測しています．

結果は，

| Language | HTTP Rest [msec] | gRPC [msec] |
|---|---|---|
| python | 7.525 | 0.751 |
| go | 6.380 | 0.551 |
| rust | 6.311 | 0.534 |

どの言語においても gRPC の方が HTTP Rest よりも 10倍程度速いのは驚きでした．また，言語間でそこまで速度に差異がないのは HTTP の処理自体がネイティブに実装されているからなのかなとも思いました．
さらに，インメモリDBの比較における性能は msec オーダーだったので，gRPC の処理による影響とはオーダーが異なり，単純とはいえどインメモリ処理の方が支配的だったと考えることができそうです．

なお，それぞれ何のライブラリを使うかによって細かな性能の違いは出てくるとは思いますが，言語間でそこまで大きな違いがないことから，大枠の傾向としてはこんな感じかなという所感です．
参考として，今回 HTTP Rest に使ったライブラリは
- python: https://a2c.bitbucket.io/flask/
- go: https://golang.org/pkg/net/http/
- rust: https://github.com/seanmonstar/warp

**Comment by ken0x0a** [comment]
試行いただきありがとうございます。

面白い結果なのですが、もしかすると
client 側の性能の限界によるものということはないでしょうか？

---

自分が REST と gRPC で比較したときにRESTの方がgRPC よりも４倍捌けたので、もう一度Simpleなものを作って試してみたところ、面白いことがわかりました。
ApacheBench や wrk を使うと 140000req / sec なのですが、
自分でBench用に reqwest （Rust の HTTP client library）を使用して試すと、 
10000 req に 7秒かかりました。
gRPC も同様に ghz を使うと 30000req / sec なのですが
tonic の client を使って試したところ
10000 req に 7秒かかりました。

結果、実際どちらが早いのかわかりませんでした。
gRPC 用にも ApacheBench のような C で書かれたツールがあればもしかすると 140000 req / sec くらいの性能が出るのかもしれませんが、 ghz (by Golang) しか良さそうなものが見つけられなかったので試すことができませんでした。

---

有名なHTTPのベンチマークによると
rust-warp と rust-actix ではパフォーマンスに約30倍の差があるそうです。
https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=plaintext

しかしおそらく、もし今回 actix を使用していただいたとしても、あまり変わらない結果になったのではないかと想像します。

---
探してみるといろいろなベンチマークをしている人がいます。
https://www.yonego.com/nl/why-milliseconds-matter/
https://medium.com/@EmperorRXF/evaluating-performance-of-rest-vs-grpc-1b8bdf0b22da
https://github.com/plutov/benchmark-grpc-protobuf-vs-http-json

Payloadの大きさを変えてみるなどいろいろなことをしている人がいるようです。
が、あまり性能は変わらないようです。
またPOST と GET でパフォーマンスが違うというのは、そういう実装になっているというだけなのではないかと感じました。
HTTPはただの平文で 冒頭 の GET か POST かが変わったところでparse する内容全体から見たら1%未満になることが多いので、URLencode と JSON のparserの性能の違いでしょうか。

**Comment by ken0x0a** [comment]
http client を都度生成してしまっていたのを使い回したりしたら
83000 req / sec まで行きました。
が、 ApacheBench と比べると 1.8倍の開きがあります。
tonic の方についても
66000 req / sec まで行きました。

Bench tool の ghz の結果を超えてしまったことから、
以前自分が ghz を使って測定したときは、限界までサーバーの能力を引き出せていなかったようです。

https://github.com/nicholasbishop/grpc-bench-rs
このbench によると
tonic よりも grpcrs の方が格段に早いみたいなので、こちらもやってみたらまた数値が変わるかもしれません。

色々やってみて、Benchmark を正しく行うためには、もっと色々環境と条件を調整したりしないといけないことがわかりました😅
